export interface Country {
  name: string;
  code: string;
  locale: string;
  flag: string;
  maxLength: number;
  mask: string; // Маска для форматирования номера
  iso: string; // ISO код страны для флагов
}

export const countries: Country[] = [
  {
    name: "Россия",
    code: "+7",
    locale: "ru-RU",
    flag: "🇷🇺",
    maxLength: 10,
    mask: "+7 (###) ###-##-##",
    iso: "ru",
  },
  {
    name: "Испания",
    code: "+34",
    locale: "es-ES",
    flag: "🇪🇸",
    maxLength: 9,
    mask: "+34 ### ### ###",
    iso: "es",
  },
  {
    name: "Канада",
    code: "+1",
    locale: "en-CA",
    flag: "🇨🇦",
    maxLength: 10,
    mask: "+1 (###) ###-####",
    iso: "ca",
  },
  {
    name: "Турция",
    code: "+90",
    locale: "tr-TR",
    flag: "🇹🇷",
    maxLength: 10,
    mask: "+90 ### ### ####",
    iso: "tr",
  },
  {
    name: "США",
    code: "+1",
    locale: "en-US",
    flag: "🇺🇸",
    maxLength: 10,
    mask: "+1 (###) ###-####",
    iso: "us",
  },
  {
    name: "Германия",
    code: "+49",
    locale: "de-DE",
    flag: "🇩🇪",
    maxLength: 11,
    mask: "+49 #### #######",
    iso: "de",
  },
  {
    name: "Франция",
    code: "+33",
    locale: "fr-FR",
    flag: "🇫🇷",
    maxLength: 9,
    mask: "+33 # ## ## ## ##",
    iso: "fr",
  },
  {
    name: "Великобритания",
    code: "+44",
    locale: "en-GB",
    flag: "🇬🇧",
    maxLength: 10,
    mask: "+44 #### ######",
    iso: "gb",
  },
  {
    name: "Италия",
    code: "+39",
    locale: "it-IT",
    flag: "🇮🇹",
    maxLength: 10,
    mask: "+39 ### ### ####",
    iso: "it",
  },
  {
    name: "Китай",
    code: "+86",
    locale: "zh-CN",
    flag: "🇨🇳",
    maxLength: 11,
    mask: "+86 ### #### ####",
    iso: "cn",
  },
  {
    name: "Япония",
    code: "+81",
    locale: "ja-JP",
    flag: "🇯🇵",
    maxLength: 10,
    mask: "+81 ## #### ####",
    iso: "jp",
  },
  {
    name: "Австралия",
    code: "+61",
    locale: "en-AU",
    flag: "🇦🇺",
    maxLength: 9,
    mask: "+61 ### ### ###",
    iso: "au",
  },
  {
    name: "Южная Корея",
    code: "+82",
    locale: "ko-KR",
    flag: "🇰🇷",
    maxLength: 10,
    mask: "+82 ## #### ####",
    iso: "kr",
  },
  {
    name: "Нидерланды",
    code: "+31",
    locale: "nl-NL",
    flag: "🇳🇱",
    maxLength: 9,
    mask: "+31 # ## ## ## ##",
    iso: "nl",
  },
  {
    name: "Бельгия",
    code: "+32",
    locale: "nl-BE",
    flag: "🇧🇪",
    maxLength: 9,
    mask: "+32 ### ## ## ##",
    iso: "be",
  },
  {
    name: "Швейцария",
    code: "+41",
    locale: "de-CH",
    flag: "🇨🇭",
    maxLength: 9,
    mask: "+41 ## ### ## ##",
    iso: "ch",
  },
  {
    name: "Швеция",
    code: "+46",
    locale: "sv-SE",
    flag: "🇸🇪",
    maxLength: 9,
    mask: "+46 ## ### ## ##",
    iso: "se",
  },
  {
    name: "Норвегия",
    code: "+47",
    locale: "no-NO",
    flag: "🇳🇴",
    maxLength: 8,
    mask: "+47 #### ####",
    iso: "no",
  },
  {
    name: "Финляндия",
    code: "+358",
    locale: "fi-FI",
    flag: "🇫🇮",
    maxLength: 9,
    mask: "+358 ## ### ####",
    iso: "fi",
  },
  {
    name: "Израиль",
    code: "+972",
    locale: "he-IL",
    flag: "🇮🇱",
    maxLength: 9,
    mask: "+972 ## ### ####",
    iso: "il",
  },
  {
    name: "ОАЭ",
    code: "+971",
    locale: "ar-AE",
    flag: "🇦🇪",
    maxLength: 9,
    mask: "+971 ## ### ####",
    iso: "ae",
  },
];
